// src/types/index.ts — re-export from canonical types/state.ts
export type {
  TripType,
  Airport,
  CityPair,
  FlightOffer,
  FareClass,
  BookingSession,
  PassengerData,
  MealOption,
  BaggageOption,
  SeatOption,
  AncillarySelection,
  SeatSelection,
  ServicesData,
  PaymentResult,
  BookingResult,
  SearchCriteria,
  AppState,
  ScreenId,
  ModalId,
  ModalState,
} from './state';
